name: Check Project Build

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-check:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t backend:latest .

      - name: Run build test
        run: |
          echo "Build succeeded!"
