name: Deploy backend on merge

on:
  push:
    branches: [ "main" ]

jobs:
  prepare-environment:
    runs-on: self-hosted # my vds
    steps:
      - name: Stop and remove containers, networks
        run: |
          docker stop backend || true
          docker rm backend || true
      - name: Remove unused data
        run: docker system prune -a -f

  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t backend:latest .

      - name: Run Docker container with latest data
        run: |
          docker run -d \
            --name backend \
            -p 8080:8080 \
            backend:latest
